CREATE TABLE IF NOT EXISTS `bb1_querchat_config` (
`ID` int(11) NOT NULL,
  `boardid` int(11) NOT NULL,
  `authhash` text NOT NULL,
  `URL` text NOT NULL,
  `islive` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `bb1_querchat_config`
 ADD PRIMARY KEY (`ID`), ADD UNIQUE KEY `ID` (`ID`);

ALTER TABLE `bb1_querchat_config`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
