CREATE TABLE IF NOT EXISTS `bb1_querchat_server_shouts` (
`ID` int(11) NOT NULL,
  `boardid` int(11) NOT NULL,
  `inhalt` text NOT NULL,
  `autor_name` text NOT NULL,
  `autor_id` int(11) NOT NULL,
  `time` text NOT NULL
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


ALTER TABLE `bb1_querchat_server_shouts`
 ADD PRIMARY KEY (`ID`);

ALTER TABLE `bb1_querchat_server_shouts`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

CREATE TABLE IF NOT EXISTS `bb1_querchat_server_boards` (
`ID` int(11) NOT NULL,
  `boardname` text NOT NULL,
  `authhash` text NOT NULL,
  `url` text NOT NULL,
  `prefix` text NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `bb1_querchat_server_boards`
 ADD PRIMARY KEY (`ID`);

ALTER TABLE `bb1_querchat_server_boards`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
